# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${hydra:runtime.choices.experiment}/${hydra:runtime.choices.model/network}/${task_name}/fold_${dataset.fold_index}/L=${model.network.num_layers}-h=${model.network.hidden_channels}

sweep:
  dir: ${paths.log_dir}
  subdir: ${hydra:runtime.choices.experiment}/${hydra:runtime.choices.model/network}/${task_name}/fold_${dataset.fold_index}/L=${model.network.num_layers}-h=${model.network.hidden_channels}
