# disable python warnings if they annoy you
ignore_warnings: false

# pretty print config tree at the start of the run using Rich library
print_config: true

# trainer plugins
plugins: null

# model state dict
state_dict_saving_params:
  symbols: 6
  exceptions: ["criterion"]

# predictions
predictions_saving_params:
  output_format: "json"
