_target_: netquant.modules.module.NodeClassificationModule

network: ???

criterion:
  _target_: torch.nn.BCEWithLogitsLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 1.0e-3
  weight_decay: 1.0e-5

scheduler:
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: max
    factor: 0.3
    min_lr: 1.0e-9
    patience: 10
    verbose: true
  extras:
    monitor: acc/valid
    interval: epoch
    frequency: 1

metrics:
  main:
    _target_: torchmetrics.Accuracy
    task: binary
  valid_best:
    _target_: torchmetrics.MaxMetric
  additional:
    auroc:
      _target_: torchmetrics.AUROC
      task: binary

logging:
  on_step: false
  on_epoch: true
  sync_dist: true
  prog_bar: true
