_target_: netquant.datasets.datamodule.DataModule

defaults:
  - _self_
  - loaders: default.yaml

dataset:
  _target_: netquant.datasets.genius.Genius

loaders:
  train:
    batch_size: 512
    num_neighbors: [4]
    num_layers: ${model.network.num_layers}
  val:
    batch_size: 512
    num_neighbors: [4]
    num_layers: ${model.network.num_layers}
  test:
    batch_size: 512
    num_neighbors: [4]
    num_layers: ${model.network.num_layers}
