_target_: netquant.datasets.datamodule.DataModule

defaults:
  - _self_
  - loaders: default.yaml

dataset:
  _target_: netquant.datasets.twitch.Twitch

loaders:
  train:
    batch_size: 64
    num_neighbors: [66]
    num_layers: ${model.network.num_layers}
  val:
    batch_size: 64
    num_neighbors: [66]
    num_layers: ${model.network.num_layers}
  test:
    batch_size: 64
    num_neighbors: [66]
    num_layers: ${model.network.num_layers}
