# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - callbacks: default
  - logger: csv
  - paths: default
  - extras: default
  - hydra: default
  - trainer: gpu
  - debug: null
  - experiment: ???

# task name, determines output directory path
task_name: "train"

# set false to skip model training
train: true

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: true
save_state_dict: true

# simply provide checkpoint path to resume training
ckpt_path: null

# name of the run, accessed by loggers
name: "nc-exp"

# seed for reproducibility
seed: 0

dataset:
  fold_index: ???
