# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: disabled
  - override job_logging: colorlog

output_subdir: null

# output directory, generated dynamically on each run
run:
  dir: ${paths.output_dir}/${hydra:runtime.choices.dataset}/${model}/fold=${fold_index}/trial=${trial}/quantification/${task_name}

sweep:
  dir: ${paths.output_dir}
  subdir: ${hydra:runtime.choices.dataset}/${model}/fold=${fold_index}/trial=${trial}/quantification/${task_name}

job:
  chdir: true
